### ISSUE TITLE
UI (CSS) bugs

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerLabs/note-app-elements#18]
Please take a look at appearance of white bar at the bottom of the page in video 1 and upward movement of the floating action button at the bottom right of the page in video 2:

https://drive.google.com/open?id=0B2RP36_VaXJVbl9VXzgyWVBXNEU
https://drive.google.com/open?id=0B2RP36_VaXJVbi1SVW9jWXVKeUk

**Comment by FluorescentHallucinogen** [comment]
@e111077 PTAL. How to fix it?

**Comment by e111077** [comment]
Heya @FluorescentHallucinogen, these elements are meant for being used as dependencies in our storage codelabs and demos for which they serve the use case fully. For extending these elements I recommend you make a fork of this repo.

For support on extending these elements I would suggest reaching out to the broader Polymer community such as on our [public slack channels](https://polymer-slack.herokuapp.com/) or on support forums such as Stack Overflow so that way other people having trouble with the same issues as you can also benefit from your solutions.

**Comment by FluorescentHallucinogen** [comment]
@e111077 It looks like you misunderstood me. I have no intention of extending (add new features to) these elements, I have an intention to fix bugs in these elements.

These bugs that I reported is caused by the fact that [the resizing behavior of the URL bar is changed in Chrome on Android starting with version 56](https://developers.google.com/web/updates/2016/12/url-bar-resizing).

**Comment by FluorescentHallucinogen** [comment]
@e111077 Could you please ping someone, who knows CSS well, from Polymer team to look and fix this bug?

**Comment by notwaldorf** [comment]
@FluorescentHallucinogen @e111077 is a core member of the Polymer team, and "knows CSS" as well as the rest of the team. He owns this repo, and we trust any decisions he makes about it. As he mentioned, these elements were written to be used in a CRUD demo, and that demo is in no way production ready. The point of the demo is to demonstrate the functionality of `app-storage`, not of random UI elements that may or may not "look" production ready. The team has over 100 elements (and therefore demos) to maintain at any given time, which means we have to prioritize issues that actually effect elements (in this case: an _actual_ issue with app-storage would be fixed, a visual UI issue with the demo is of significant less importance). As Elliott mentioned, if you have a fix for this, or someone from the community does, it will probably get looked at, but we don't have any resources at the moment to allocate to this issue, which is why he closed it.
